### ISSUE TITLE
Bug with F2

### ISSUE THREAD

**Issue by thiagolopes** [ThiagoLopes/vim-master#10]
Quando o NerdTree está aberto o comportamento do <F2> está fechando o vim, com o NerdTree ocultado ele funciona normalmente.

@cacarrara pode ser alguma configuração do NerdTab?

**Comment by caiocarrara** [comment]
Hey, let's keep project related dialog in english.

So, here the F2 isn't closing vim. What are the steps to reproduce it?

**Comment by thiagolopes** [comment]
Faça essa naveção
```
<F1>
<C-W> <C-W>
<F2>
```
Resumindo: Abra o vim, abra o NerdTree, mude o cursor para a buffer, e tente fechar ele com F2, com o NerdTree aberto

**Comment by caiocarrara** [comment]
Everything work well here...

**Comment by caiocarrara** [comment]
You need to close it.

**Comment by thiagolopes** [comment]
Now work. closed
